"""Prompt library for the Dynamic Research Assistant."""

from .prompt import (
    SYSTEM_PROMPT,
    ORCHESTRATOR_PROMPT,
    WEB_SEARCH_PROMPT,
    SUMMARIZATION_PROMPT,
    FACT_CHECKING_PROMPT,
    DATA_EXTRACTION_PROMPT,
    CITATION_PROMPT,
    CONVERSATION_MEMORY_PROMPT
)

__all__ = [
    "SYSTEM_PROMPT",
    "ORCHESTRATOR_PROMPT", 
    "WEB_SEARCH_PROMPT",
    "SUMMARIZATION_PROMPT",
    "FACT_CHECKING_PROMPT",
    "DATA_EXTRACTION_PROMPT",
    "CITATION_PROMPT",
    "CONVERSATION_MEMORY_PROMPT"
]